[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.dev]
  # cache Cypress binary in local "node_modules" folder
  # so Netlify caches it
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  # set TERM variable for terminal output
  TERM = "xterm"

[[plugins]]
# local Cypress plugin will test our site after it is built
package = "netlify-plugin-cypress"
  [plugins.inputs]
    # can also use "spa = true" to use "index.html" by default
    skip = true
  [plugins.inputs.onSuccess]
    # run tests after the deploy
    enable = true
    spa = "index.html"
    record = true